extends: default

yaml-files:
  - "*.y{a,}ml"

ignore:
  - .git
  - .mypy_cache
  - .pytest_cache
  - .ruff_cache
  - .venv

rules:
  braces:
    forbid: true
    level: warning
  brackets:
    forbid: false
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  document-end:
    present: false
    level: warning
  document-start:
    present: false
    level: warning
  indentation:
    spaces: 2
  line-length:
    max: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
    level: warning
    ignore:
      - .github/workflows/*.y{a,}ml
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  quoted-strings:
    quote-type: double
    required: only-when-needed
  trailing-spaces:
    level: warning
  truthy:
    ignore:
      - .github/workflows/*.y{a,}ml
