[build-system]
requires      = [ "hatchling", "hatch-vcs" ]
build-backend = "hatchling.build"

[project]
name = "github-action-workflows"
dynamic = [ "version" ] # Version comes from Git tags
description = "GitHub action workflow demos"
readme = "README.md"
license="MIT"
authors = [
    { name = "Dirk Sidney Jansen", email = "sidisinsane@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
  "pyyaml~=6.0.2",
]

[project.urls]
Homepage      = "https://github.com/sidisinsane/github-action-workflowss"
Documentation = "https://github.com/sidisinsane/github-action-workflows#readme"
Repository    = "https://github.com/sidisinsane/github-action-workflows.git"
"Bug Tracker" = "https://github.com/sidisinsane/github-action-workflows/issues"

[project.optional-dependencies]
build = [ "python-semantic-release~=10.3.1" ]

[project.scripts]
github-action-workflows = "github_action_workflows:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = [ "src/github_action_workflows" ]

[tool.hatch.build.hooks.vcs]
version-file = "src/github_action_workflows/__version__.py"
version-scheme = "guess-next-dev"
local-scheme = "no-local-version"
fallback-version = "0.1.0"
template = '''"""Package version information.

Automatic version file generated by hatch-vcs. Do not change, do not track!
"""

from __future__ import annotations


__version__ = {version!r}
__version_tuple__ = {version_tuple!r}

'''

[tool.semantic_release]
build_command = """
  uv lock --upgrade-package "$PACKAGE_NAME"
  uv build
"""
commit_message = "chore(release): {version}\n\n{changelog}"
commit_author = "semantic-release <semantic-release>"
tag_format = "{version}"

