name: Demo

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.3.0

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4.0.0

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          uv sync --extra build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test project script
        run: uv run github-action-workflows
