name: Manually Triggered Demo Workflow

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
      environment:
        description: Target environment
        required: false
        default: staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.3.0

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4.0.0

      - name: Cache dependencies
        uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          uv sync --extra build

      - name: Test project script
        run: uv run github-action-workflows
