# yamllint disable rule:line-length
name: Documentation

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.3.0
        with:
          fetch-depth: 0

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4.0.0

      - name: Cache dependencies
        uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          uv sync --extra docs

      - name: Build docs
        run: make docs-build

      - name: Test build
        run: |
          test -d site || (echo "MkDocs build failed: site/ not found" && exit 1)
          test -d site/reference || (echo "Sphinx build failed: site/reference/ not found" && exit 1)
          echo "Both documentation builds successful"

      - name: Deploy docs
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
