# yamllint disable rule:line-length
name: Documentation

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.set-outputs.outputs.artifact-path }}
      commit-sha: ${{ steps.set-outputs.outputs.commit-sha }}
      site-version: ${{ steps.set-outputs.outputs.site-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.3.0
        with:
          fetch-depth: 0

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4.0.0

      - name: Cache dependencies
        uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          uv sync --extra docs

      - name: Build docs
        id: build-docs
        run: make docs-build

      - name: Set job outputs
        id: set-outputs
        run: |
          echo "artifact-path=site" >> "$GITHUB_OUTPUT"
          echo "commit-sha=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          echo "site-version=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: site

  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
    steps:
      - name: Check if GitHub Pages is enabled
        id: check-pages
        run: |
          echo "Checking if GitHub Pages is enabled..."
          api_url="https://api.github.com/repos/${{ github.repository }}/pages"
          status=$(curl -s -o response.json -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "$api_url")

          if [ "$status" -ne 200 ]; then
            echo "error=not_enabled" >> "$GITHUB_OUTPUT"
            echo "::error::GitHub Pages is not enabled for this repository."
            echo "👉 Please go to Settings → Pages → Build and deployment and select 'GitHub Actions'."
            exit 1
          else
            echo "Pages API is accessible. Proceeding with deployment."
          fi

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5

      - name: Print deployment metadata
        run: |
          echo "Artifact path: ${{ needs.build.outputs.artifact-path }}"
          echo "Commit SHA:    ${{ needs.build.outputs.commit-sha }}"
          echo "Site version:  ${{ needs.build.outputs.site-version }}"
